### ISSUE TITLE
Eddy doesn't run with RPE None

### ISSUE THREAD

**Issue by TheJaeger** [m-ama/PyDesigner#10]
Users have the option of performing eddy motion correction only without topup with the flag -rpe_none. While not needed for motion correction, this still requires a phase encoding (PE) direction. Current implementation for motion correction only works with the flag `-eddy -rpe-none -pe_dir j`, where j is the PE direction.

It would be nice to not specify a PE direction if no topup is being run such that the above flasg becomes `-eddy  -rpe_none`. Be wary though as this may be an MRTRIX3 limitation rather than designer itself.

**Comment by jbteves** [comment]
Was closed in #92
