### ISSUE TITLE
dwipreproc error with --undistort & --rpe_none options

### ISSUE THREAD

**Issue by vadisetiyo** [m-ama/PyDesigner#101]
**Describe the Issue**
Dataset: 2 DKI averages, 1 extra set of B0 averages
Goal: Run PyDesigner with --undisort and --rpe_non options in order to register/align all my averages prior to DKI map calculation to improve map quality
Issue: Unable to process dataset and get dwipreproc error (see attached jpg)

**Issue Reproduction**
Dataset available in shared Box: All Files/PyDesigner_Testing/dwipreproc_Error/4042
Command ran: $ python /Users/adisetiyo/Desktop/PyDesigner/Software/PyDesigner/designer/pydesigner.py --denoise --undistort --smooth --rician --mask --rpe_none --verbose -o /Users/adisetiyo/Desktop/PyDesigner/4042/DKI_outputs /Users/adisetiyo/Desktop/PyDesigner/4042/DKI_inputs/4042_DIFF_siemens_dir_27_AVE1.nii,/Users/adisetiyo/Desktop/PyDesigner/4042/DKI_inputs/4042_DIFF_siemens_dir_27_AVE2.nii,/Users/adisetiyo/Desktop/PyDesigner/4042/DKI_inputs/4042_DKI_B0.nii

**Supplemental Information**
OS: macOS Mojave Version 10.14.5
See attached snapshots for 1) Error; 2) System set up 

<img width="649" alt="10 28 19_dwipreprocError" src="https://user-images.githubusercontent.com/50455249/67708102-fbb49200-f991-11e9-978a-cea65422872a.png">

<img width="599" alt="10 28 19_PackageVersions" src="https://user-images.githubusercontent.com/50455249/67708142-0a02ae00-f992-11e9-91fb-adf26f54fb3a.png">

**Comment by jbteves** [comment]
Hi Vitria, this is I believe a known bug on OS X. You'll have to run it on a Linux docker environment. We should absolutely prioritize making a dockerfile and adding it to instructions. If you have a Linux partition you'll see it runs fine. Sorry, I think it totally slipped my mind to point this out in the meeting we had today. 
@TheJaeger do you have a dockerfile already to kickstart this?

**Comment by TheJaeger** [comment]
I'll invite you to collab on our dockerfile project. We can actually start kicking it off now that we have a somewhat working pipeline; dockerfiles stay somewhat the same once repos are defined.

**Comment by TheJaeger** [comment]
Issue was isolated to be an OS error. Refer to internal conversation below:

![Screen Shot 2019-11-11 at 11 28 44 AM](https://user-images.githubusercontent.com/13654344/68722104-7977c080-0582-11ea-8570-3275042ba7a2.png)

The important information in this log is the third line from the bottom that says dwipreproc: [WARNING] CUDA version of eddy appears to have failed; trying OpenMP version.  This warning implies that your machine doesn't support CUDA, so it runs the OpenMP  version of eddy. This should be the correct behavior on non-CUDA devices like our Macs.
