### ISSUE TITLE
Pydesigner cannot find mrtrix3

### ISSUE THREAD

**Issue by abnormally-distributed** [m-ama/PyDesigner#154]
I am attempting to run pydesigner, but am encountering an issue with mrtrix3. mrtrix3 has been built successfully, and appears in my PATH. However, trying to run pydesigner results in the below error message.  Might anyone be able to provide some insight on this issue, and how I can solve it?

```
Traceback (most recent call last):
  File "pydesigner.py", line 24, in <module>
    raise Exception('Cannot find mrtrix3, please see '
Exception: Cannot find mrtrix3, please see https://github.com/m-ama/PyDesigner/wiki to troubleshoot.

```
The information at the [mrtrix website](https://mrtrix.readthedocs.io/en/latest/installation/linux_install.html) didn't resolve the issue.

Here is the system information:

- RAM: 31.4 GB
- Processor: Intel Xeon CPU E5-2697 v4 @ 2.3 Ghz x 10
- GNOME version: 3.28.2
- OS type: 64 bit
- Virtualization: VMware

**Comment by TheJaeger** [comment]
Try running `mrinfo -h` in terminal. If it doesn't print the _mrinfo_ help text, your installation of MRtrix3 is incomplete.

**Comment by TheJaeger** [comment]
Stale Issue. Closing.
