### ISSUE TITLE
Enable `.fib` output for DSI

### ISSUE THREAD

**Issue by TheJaeger** [m-ama/PyDesigner#180]
Some groups prefer fiber tracking with DSI Studio, and have requested that `.fib` files be added to PyD.

**Comment by gonzoBlackMamba** [comment]
This would be nice to also implement  for the pyFBI. I know that Leo's group wants .fib files for FBI data. I can do it in MATLAB but it is clunky with the new FBWM modeling.

**Comment by TheJaeger** [comment]
We can definitely do this.

**Comment by TheJaeger** [comment]
.fib file added for FBI.
