### ISSUE TITLE
Deprecate CVXOPT

### ISSUE THREAD

**Issue by TheJaeger** [m-ama/PyDesigner#19]
Use CVXPY in its favor because it's easier to build and install.

**Comment by jbteves** [comment]
Did your latest PR fix this?

**Comment by TheJaeger** [comment]
Nope. This is a very low-priority for now because CVXPY is a little more challenging to code. It took me a long file to get LLS to work and frankly speaking I don't want to do it again anytime soon.

**Comment by TheJaeger** [comment]
Closing this issue for now since it's trivial and a matter of preference.

**Comment by TheJaeger** [comment]
It appears that `CVXOPT` does not apply constraints correctly in comparison to `CVXPY`. Issue reopened until a fix is implemented.
