### ISSUE TITLE
Validate WMTI metrics

### ISSUE THREAD

**Issue by TheJaeger** [m-ama/PyDesigner#199]
**Describe the Issue**

WMTI metrics have not yet been validated, so we're unsure whether PyD is producing the correct values.

**Comment by gonzoBlackMamba** [comment]
@TheJaeger: If we have some healthy control data, we could run it through DKE WMTI and the compare PyD WMTI to that output, right?

**Comment by TheJaeger** [comment]
@gonzoBlackMamba I have been doing that and found WM tissue values to be very close, and even same at some voxels, between DKE and PyD. However, PyD is more susceptible to partial-volume effects so CSF-tissue interface values are difference.

That said, I don't have much working experience with WMM/WMTI, hence why I need validation help. I am not very confident in my evaluation.

**Comment by gonzoBlackMamba** [comment]
@TheJaeger As far as I understand it, WMTI assumes parallel aligned WM fibers so it will most likely only be valid within major WM tracts like the corpus callosum, the posterior limb of the internal capsule and the cortical spinal tract or similar regions. If those regions are similar or consistent in their values, then I think it is a good indication for validity within PyD's framework. Jens would also be able to comment on this as well.

**Comment by TheJaeger** [comment]
WMTI metrics were compared against legacy software DKI and found to be reliable. Having said that, WMTI is still not as accurate as fiber ball imaging (FBI) for white matter parameterization. Hence, FBI will supersede WMTI in release v1.0_RC1
