### ISSUE TITLE
OSError: Input data is not currently supported by PyDesigner

### ISSUE THREAD

**Issue by cowry09** [m-ama/PyDesigner#231]
Very exciting project. 
Forgive my ignorance, as a first time user here, wonder if there are example data available to test whether the NeuroDock and PyDesigner are correctly installed. I was pulling the latest pre-built NeuroDock to conduct the practical run on DKI dicom data, downloaded from NITRC: https://www.nitrc.org/projects/dke/

The dicom file was converted by dcm2nii in MRIcron, and it generated the following files '*.nii.gz', '*.jason', '*.bval','*.bvec'. Runing the example script in the manual on those files (https://pydesigner.readthedocs.io/en/latest/docker/docker_neurodock_run.html). The following error was found: 

  File "/usr/local/bin/pydesigner", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/designer/pydesigner.py", line 234, in main
    image = DWIParser(args.dwi)
  File "/usr/local/lib/python3.7/dist-packages/designer/preprocessing/util.py", line 436, in __init__
    ftype.append(mrinfoutil.format(self.DWIlist[i]).lower())
  File "/usr/local/lib/python3.7/dist-packages/designer/preprocessing/mrinfoutil.py", line 61, in format
    type = getconsole(path, '-format')
  File "/usr/local/lib/python3.7/dist-packages/designer/preprocessing/mrinfoutil.py", line 41, in getconsole
    'PyDesigner.'.format(path))

OSError: Input /data/nifti/dki_example_data_nifti_DKI_B0_20120101135601_8.nii.gz is not currently supported by PyDesigner.

What went wrong?

**Comment by TheJaeger** [comment]
Hello! Thanks for reaching out to us!

Before we begin troubleshooting, it would help that you post the PyDesigner version within NeuroDock. You can get this with a command:

```
docker run -it --rm dmri/neurodock:latest pydesigner -v
```

**Comment by cowry09** [comment]
Thanks for the quick return. The version is:
v1.0-RC4

**Comment by TheJaeger** [comment]
You shouldn't have that issue with v1.0-RC4. Could you also paste the command you typed into your CLI terminal, as well as a screenshot of all files accompanying _dki_example_data_nifti_DKI_B0_20120101135601_8.nii.gz_?

**Comment by cowry09** [comment]
The command:

docker run -it --rm -v C:/Desktop/DryRun_DKI:/data dmri/neurodock pydesigner --standard --output /data/processed /data/nifti/dki_example_data_nifti_DKI2_20120101135601_5.nii.gz,dki_example_data_nifti_DKI_B0_20120101135601_8.nii.gz,dki_example_data_nifti_DKI1_20120101135601_2.nii.gz

The files in the 'nifti' folder:

![Capture](https://user-images.githubusercontent.com/50677308/96353041-848e7700-1096-11eb-8a4d-4fc78c1ec429.PNG)

Many thanks!

**Comment by TheJaeger** [comment]
Hi @cowry09! Sorry for the late response. Our lab is in the process of moving so replies may take a while.

I replicated your steps (incl. conversion with `dcm2niix`) but everything processed perfectly on my end. I think this may be a path related issue on Windows. Could you run your command again with the addition of the `--verbose` flag? This way _MRTrix3_ will print warnings and errors as well so we could have more information on what's going wrong.

**Comment by cowry09** [comment]
I did run the command with the --verbose flag, it gave me the same error message. I repeated the process on another win 10 computer and it errored out in the same way. I will try it on an ubuntu machine to see if works, otherwise it must be my mistake.

**Comment by TheJaeger** [comment]
@cowry09 it should have produced more errors before:

```
OSError: Input /data/nifti/dki_example_data_nifti_DKI_B0_20120101135601_8.nii.gz is not currently supported by PyDesigner.
```

PyDesigner produces this error when something on MRTrix3's end fails. There should also be an error from MRTrix3 before this error that will help diagnose the issue, which is what I need. Another thing you could do it to test uncompressed nifti files with just the `.nii` extension instead of `.nii.gz`. I've faced similar issues running Docker on Windows when using compressed NifTi files.

**Comment by cowry09** [comment]
Thanks @TheJaeger for your patience in resolving this issue. As of now, the command is running. 

I was able to run the code after upgrading the windows system and using the Docker Desktop WSL 2 backend
https://docs.docker.com/docker-for-windows/wsl/
![image](https://user-images.githubusercontent.com/50677308/96828918-7a59d900-1406-11eb-8440-4390c875459f.png)

**Comment by TheJaeger** [comment]
@cowry09 well, that was an unexpected fix. I'll add it to our FAQ for Windows users.
