### ISSUE TITLE
How do I load phase encoding images (AP and PA) for eddy currents correction.

### ISSUE THREAD

**Issue by LRAlvarado** [m-ama/PyDesigner#236]
Hi all,

I am running PyDesigner via Neurodock v1.0-RC5. I am trying to run a single subject with the dataset organized as per BIDS. I have AP and PA phase encoding images that I would normally use in FSL for eddy correction. While trying to load them into the docker as follows:
```
docker run -it --rm \
    -v /Users/lralvarado/Scratch_Disk/supraspinal_study/analysis/MRI/BIDS:/data:ro \
    -v /Users/lralvarado/Scratch_Disk/supraspinal_study/analysis/MRI/derivatives/PyDesigner:/out \
    dmri/neurodock pydesigner \
    --standard \
    --verbose \
    --output /out/processed \
    /data/sub-K327/ses-pedsSCI001/dwi/sub-K327_ses-pedsSCI001_acq-64dir_dwi.nii.gz,\
    /data/sub-K327/ses-pedsSCI001/fmap/sub-K327_ses-pedsSCI001_acq-dwiAP_epi.nii.gz,\
    /data/sub-K327/ses-pedsSCI001/fmap/sub-K327_ses-pedsSCI001_acq-dwiPA_epi.nii.gz
```
I get the following error:
`pydesigner: error: unrecognized arguments: /data/sub-K327/ses-pedsSCI001/fmap/sub-K327_ses-pedsSCI001_acq-dwiAP_epi.nii.gz, /data/sub-K327/ses-pedsSCI001/fmap/sub-K327_ses-pedsSCI001_acq-dwiPA_epi.nii.gz`

Is there a way to pass these images through?

**Comment by TheJaeger** [comment]
Hi @LRAlvarado, you would simple give it all your scanning sequences separated by a comma such that it reads `$DWI1,$DWI2,...,$DWIn` in a single string. There should be no space separating your inputs. In your case, try removing the `\` slash to see if it helps. Docker can be quite finicky something especially on Windows systems.

**Comment by LRAlvarado** [comment]
Thank you, @TheJaeger. 
I think the problem was the lack of accompanying bvals and bvecs files for my AP and PA images.

**Comment by TheJaeger** [comment]
@LRAlvarado well I totally overlooked your dataset. It's fantastic you got it to work. Let us know if you'd like additional features to be implemented, we'd be more than happy to work them in for you.
