### ISSUE TITLE
PyDesigner not compatible with SynB0-DISCO outputs

### ISSUE THREAD

**Issue by ryn-thorn** [m-ama/PyDesigner#259]
**Describe the Issue**

SynB0-DISCO's synthetic B0 outputs should be used as a predefined topup target to compute a distortion field as opposed to PyDesigner's current method of using two reverse PE B0s to compute an inverse distortion field. As a result, SynB0-DISCO's synthetic B0 cannot be used as intended on datasets for which topup was not acquired. 

**Issue Reproduction**
```
python pydesigner -o /output/path -s --force /Path/to/dwi_raw.nii,/path/to/synthetic_b0.nii
dwipreproc: [WARNING] Command failed: eddy_cuda --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --repol --data_is_shelled --out=dwi_post_eddy
dwipreproc: [WARNING] CUDA version of eddy appears to have failed; trying OpenMP version`
```

**Comment by TheJaeger** [comment]
Closing stale issue
