### ISSUE TITLE
tensor type

### ISSUE THREAD

**Issue by YuchuanQiao** [m-ama/PyDesigner#262]
def tensorType(self):
        """
        Returns whether input image is DTI or DKI compatible, requires
        no input parameters

        Returns
        -------
        list of str
            contains list of string 'dti', 'dki', or 'fbi' based on
            the protocols the input DWI represents

        Examples
        --------
        a = dwi.tensorType(), where dwi is the DWI class object
        """
        type = []
        _if self.maxDTIBval() <= th.__maxdtibval__ and \
            self.maxDTIBval() >= th.__mindkibval__:
            type.append('dti')
        if self.maxDKIBval() >= th.__maxdtibval__ and \
            self.maxDKIBval() <= th.__maxdkibval__:
            type.append('dki')

Hi, is that possible for the detection of one dki file is detected as DTI and also DKI?
I got the detection output is 
   Protocol(s) detected: DTI, DKI.
Thanks.

**Comment by TheJaeger** [comment]
Hi @YuchuanQiao, that is correct, it will tag DKI protocols as DTI as well due to the presence of three b-valie shells. 

PyDesigner makes a distinction between the two to apply corrections that are dependent whether the tensor has 6 (DTI) or 21 (DKI) volumes.

**Comment by YuchuanQiao** [comment]
@TheJaeger Thanks for the clarify, what should I do if I want to calculate the fiber tracts with DKI image? Could I just use MRtrix with the preprocessed data by PyDesigner?

**Comment by TheJaeger** [comment]
You may skip DTI/DKI parameter extraction with the `--no_fit` flag and use the preprocessed file _dwi_preprocessed.nii_ to do tractography with MRtrix. Likewise, it is recommended you use MRtrix3 for both tensor estimation and parameter extraction so your results are consistent.

**Comment by YuchuanQiao** [comment]
Good to know. Thank you very much!
