### ISSUE TITLE
AKC Outlier Detection: 

### ISSUE THREAD

**Issue by override641** [m-ama/PyDesigner#278]
Now I started getting stuck at AKC Outlier Detection: . it doesn't report any error, just returns me back to bash. even on images I've already processed earlier.

**Comment by override641** [comment]
this error stopped occuring without me doing anything

**Comment by TheJaeger** [comment]
I reckon this is occurring due to a lack of memory since AKC is an extremely memory-intensive brute-force technique. Increasing your virtual memory may resolve the issue.
