### ISSUE TITLE
Add number of workers option

### ISSUE THREAD

**Issue by TheJaeger** [m-ama/PyDesigner#31]
Add flag that allows users to define number of cores to use in processing. Default should be all available cores.

Use the `multiprocessing` library to manage thread detection:
```
import multiprocessing
num_cores = multiprocessing.cpu_count()
```

**Comment by jbteves** [comment]
Default should always be only one. On managed systems you may not be allowed to request more, or may prefer running many jobs in parallel instead.

**Comment by TheJaeger** [comment]
Fair point, and I agree after thinking about it. Set default to one.

I would still add an option something like `all` that does full load. There are researchers out there who don't know what cores or threads are, or some who just need to process a few subjects. For those, enabling all cores easily would be a good thing imo.

**Comment by jbteves** [comment]
They can RTFM. For auto-detection they can supply `-1`

**Comment by TheJaeger** [comment]
LOL! `-1` works for me. I'll enable a worker flag for dwipi as well so you can pass that on for tensor fitting.
