### ISSUE TITLE
Force flag doesn't run rician correction

### ISSUE THREAD

**Issue by kaytiii** [m-ama/PyDesigner#64]
--force won't run rician correction and returns the error: 

$ python pydesigner.py --denoise --degibbs --smooth --rician --force --verbose file.nii -o outfolder
Given DWI is partial fourier, overriding --degibbs; no unringing correction will be done to avoid artifacts.
dwidenoise: [WARNING] existing output files will be overwritten
dwidenoise: [100%] preloading data for "/Users/kayti/Desktop/Projects/DESIGNER/KTGFDesignerTest/Data/5001/nifti/DIFF_siemens_dir_2_7_AVE2.nii"
dwidenoise: [100%] running MP-PCA denoising
Traceback (most recent call last):
  File "/Users/kayti/Repos/PyDesigner/designer/pydesigner.py", line 492, in <module>
    raise Exception('Running rician correction would cause an '
Exception: Running rician correction would cause an overwrite. In order to run this please delete the files, use --force, use --resume, or change output destination.

**Comment by TheJaeger** [comment]
Fixed by PR # 66
